// <auto-generated />
using Book.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Book.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.7.23375.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Book.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "SciFi"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "History"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "Mystery"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 6,
                            Name = "Romance"
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 7,
                            Name = "Thriller"
                        },
                        new
                        {
                            Id = 8,
                            DisplayOrder = 8,
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 9,
                            DisplayOrder = 9,
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 10,
                            DisplayOrder = 10,
                            Name = "Historical Fiction"
                        },
                        new
                        {
                            Id = 11,
                            DisplayOrder = 11,
                            Name = "Science"
                        });
                });

            modelBuilder.Entity("Book.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ListPrice")
                        .HasColumnType("float");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Price100")
                        .HasColumnType("float");

                    b.Property<double>("Price50")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "J.K. Rowling",
                            CategoryId = 2,
                            Description = "The first book in the Harry Potter series, following the young wizard Harry as he embarks on a magical journey.",
                            ISBN = "9780439554930",
                            ImageUrl = "",
                            ListPrice = 20.0,
                            Price = 15.0,
                            Price100 = 10.0,
                            Price50 = 12.0,
                            Title = "Harry Potter"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Dan Brown",
                            CategoryId = 7,
                            Description = "A thriller novel that combines art, history, and religion, following Robert Langdon as he unravels a mystery.",
                            ISBN = "9780385504201",
                            ImageUrl = "",
                            ListPrice = 25.0,
                            Price = 20.0,
                            Price100 = 15.0,
                            Price50 = 18.0,
                            Title = "The Da Vinci Code"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Jane Austen",
                            CategoryId = 6,
                            Description = "A classic romance novel that explores societal norms and love through the story of Elizabeth Bennet and Mr. Darcy.",
                            ISBN = "9780141439518",
                            ImageUrl = "",
                            ListPrice = 15.0,
                            Price = 12.0,
                            Price100 = 8.0,
                            Price50 = 10.0,
                            Title = "Pride and Prejudice"
                        },
                        new
                        {
                            Id = 4,
                            Author = "J.R.R. Tolkien",
                            CategoryId = 5,
                            Description = "The first book in The Lord of the Rings trilogy, following the journey of Frodo Baggins to destroy the One Ring.",
                            ISBN = "9780618346257",
                            ImageUrl = "",
                            ListPrice = 18.0,
                            Price = 14.0,
                            Price100 = 10.0,
                            Price50 = 12.0,
                            Title = "The Lord of the Rings"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Gillian Flynn",
                            CategoryId = 4,
                            Description = "A psychological thriller that delves into the complexities of a marriage and the mystery behind a woman's disappearance.",
                            ISBN = "9780307588364",
                            ImageUrl = "",
                            ListPrice = 17.0,
                            Price = 14.0,
                            Price100 = 10.0,
                            Price50 = 12.0,
                            Title = "Gone Girl"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Orson Scott Card",
                            CategoryId = 11,
                            Description = "A science fiction novel that follows the story of Ender Wiggin, a young boy trained in a military academy to fight against an alien species.",
                            ISBN = "9780812550702",
                            ImageUrl = "",
                            ListPrice = 12.0,
                            Price = 10.0,
                            Price100 = 7.0,
                            Price50 = 8.0,
                            Title = "Ender's Game"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Stephen King",
                            CategoryId = 8,
                            Description = "A horror novel that follows a family's terrifying experiences in an isolated hotel during the winter.",
                            ISBN = "9780385121675",
                            ImageUrl = "",
                            ListPrice = 22.0,
                            Price = 18.0,
                            Price100 = 12.0,
                            Price50 = 15.0,
                            Title = "The Shining"
                        },
                        new
                        {
                            Id = 8,
                            Author = "Andy Weir",
                            CategoryId = 11,
                            Description = "A science fiction novel about an astronaut's struggle to survive on Mars after being left behind by his crew.",
                            ISBN = "9780553418026",
                            ImageUrl = "",
                            ListPrice = 16.0,
                            Price = 14.0,
                            Price100 = 10.0,
                            Price50 = 12.0,
                            Title = "The Martian"
                        },
                        new
                        {
                            Id = 9,
                            Author = "Paula Hawkins",
                            CategoryId = 4,
                            Description = "A psychological thriller that revolves around the lives of three women and a mystery that unfolds through their perspectives.",
                            ISBN = "9781594634024",
                            ImageUrl = "",
                            ListPrice = 19.0,
                            Price = 15.0,
                            Price100 = 11.0,
                            Price50 = 13.0,
                            Title = "The Girl on the Train"
                        },
                        new
                        {
                            Id = 10,
                            Author = "J.R.R. Tolkien",
                            CategoryId = 5,
                            Description = "A fantasy adventure novel that follows Bilbo Baggins on his journey to help a group of dwarves reclaim their homeland.",
                            ISBN = "9780547928227",
                            ImageUrl = "",
                            ListPrice = 21.0,
                            Price = 18.0,
                            Price100 = 14.0,
                            Price50 = 16.0,
                            Title = "The Hobbit"
                        });
                });

            modelBuilder.Entity("Book.Models.Product", b =>
                {
                    b.HasOne("Book.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
